sudo: false

cache:
  directories:
    - tests/elm-stuff/build-artifacts
    - sysconfcpus

os:
  - linux
  - osx

env:
  matrix:
    - TARGET_NODE_VERSION=node

before_install:
  - if [ ${TRAVIS_OS_NAME} == "osx" ];
    then brew update; brew install nvm; mkdir ~/.nvm; export NVM_DIR=~/.nvm; source $(brew --prefix nvm)/nvm.sh;
    fi
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

install:
  - nvm install $TARGET_NODE_VERSION
  - nvm use $TARGET_NODE_VERSION
  - node --version
  - npm --version
  - npm install -g elm elm-format@0.7.0-exp

script:
  - elm-format --validate src tests examples
  - elm --version
  - elm make --output=/dev/null
  - cd examples
